package com.homelab.core.service.module.sql

import com.homelab.sdk.data.AutoGeneratedColumn
import com.homelab.sdk.data.AutoGeneratedType
import com.homelab.sdk.data.ColumnDefinition
import com.homelab.sdk.data.ColumnTyping
import com.homelab.sdk.data.TableDefinition
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class ObjectTableGenerateTest {

    @Test
    fun `buildCreateTableSql includes autogenerated id created_at updated_at and file columns`() {
        val definition = TableDefinition(
            name = "photos",
            columns = listOf(ColumnDefinition("title", ColumnTyping.string)),
            autoGeneratedColumns = listOf(
                AutoGeneratedColumn(AutoGeneratedType.ID),
                AutoGeneratedColumn(AutoGeneratedType.CREATED_AT),
                AutoGeneratedColumn(AutoGeneratedType.UPDATED_AT),
                AutoGeneratedColumn(AutoGeneratedType.FILE)
            )
        )

        val sql = ObjectTableGenerate.buildCreateTableSql("mod_photos", "photos", definition)

        assertTrue(sql.contains("""CREATE TABLE IF NOT EXISTS "mod_photos"."photos""""))
        assertTrue(sql.contains("id UUID PRIMARY KEY DEFAULT gen_random_uuid()"))
        assertTrue(sql.contains("created_at TIMESTAMP NOT NULL DEFAULT now()"))
        assertTrue(sql.contains("updated_at TIMESTAMP NOT NULL DEFAULT now()"))
        assertTrue(sql.contains("file VARCHAR(526)"))
        assertTrue(sql.contains("file_name VARCHAR(256)"))
        assertTrue(sql.contains(""""title" VARCHAR(1028)"""))
    }

    @Test
    fun `buildCreateTableSql does not duplicate an id column already declared explicitly`() {
        val definition = TableDefinition(
            name = "photos",
            columns = listOf(ColumnDefinition("id", ColumnTyping.string, unique = true, nullable = false)),
            autoGeneratedColumns = listOf(AutoGeneratedColumn(AutoGeneratedType.ID))
        )

        val sql = ObjectTableGenerate.buildCreateTableSql("mod_photos", "photos", definition)

        assertTrue(!sql.contains("gen_random_uuid()"))
        assertTrue(sql.contains(""""id" VARCHAR(1028) NOT NULL UNIQUE"""))
    }

    @Test
    fun `buildCreateTableSql marks non-nullable and unique columns accordingly`() {
        val definition = TableDefinition(
            name = "users",
            columns = listOf(ColumnDefinition("email", ColumnTyping.string, unique = true, nullable = false)),
            autoGeneratedColumns = emptyList()
        )

        val sql = ObjectTableGenerate.buildCreateTableSql("mod", "users", definition)

        assertTrue(sql.contains(""""email" VARCHAR(1028) NOT NULL UNIQUE"""))
    }

    @Test
    fun `buildAddColumnSql rejects a non-nullable column`() {
        val column = ColumnDefinition("count", ColumnTyping.int, nullable = false)

        assertThrows(IllegalArgumentException::class.java) {
            ObjectTableGenerate.buildAddColumnSql("mod", "photos", column)
        }
    }

    @Test
    fun `buildAddColumnSql produces an ALTER TABLE ADD COLUMN statement`() {
        val column = ColumnDefinition("count", ColumnTyping.int, nullable = true)

        val sql = ObjectTableGenerate.buildAddColumnSql("mod", "photos", column)

        assertEquals("""ALTER TABLE "mod"."photos" ADD COLUMN IF NOT EXISTS "count" INTEGER""", sql)
    }

    @Test
    fun `buildRenameColumnSql sanitizes both names`() {
        val sql = ObjectTableGenerate.buildRenameColumnSql("mod", "photos", "Old Name", "New Name")

        assertEquals("""ALTER TABLE "mod"."photos" RENAME COLUMN "old_name" TO "new_name"""", sql)
    }

    @Test
    fun `buildRetypeColumnSql uses a USING cast`() {
        val sql = ObjectTableGenerate.buildRetypeColumnSql("mod", "photos", "count", ColumnTyping.long)

        assertEquals("""ALTER TABLE "mod"."photos" ALTER COLUMN "count" TYPE BIGINT USING "count"::BIGINT""", sql)
    }

    @Test
    fun `buildRenameTableSql sanitizes both table names`() {
        val sql = ObjectTableGenerate.buildRenameTableSql("mod", "Old Table", "New Table")

        assertEquals("""ALTER TABLE "mod"."old_table" RENAME TO "new_table"""", sql)
    }

    @Test
    fun `sqlTypeFor maps every column typing to its SQL type`() {
        assertEquals("VARCHAR(1028)", ObjectTableGenerate.sqlTypeFor(ColumnTyping.string))
        assertEquals("INTEGER", ObjectTableGenerate.sqlTypeFor(ColumnTyping.int))
        assertEquals("BIGINT", ObjectTableGenerate.sqlTypeFor(ColumnTyping.long))
        assertEquals("BOOLEAN", ObjectTableGenerate.sqlTypeFor(ColumnTyping.boolean))
        assertEquals("DATE", ObjectTableGenerate.sqlTypeFor(ColumnTyping.date))
        assertEquals("TIMESTAMP", ObjectTableGenerate.sqlTypeFor(ColumnTyping.datetime))
    }

    @Test
    fun `sqlTypeFor throws for the file column typing which has no direct SQL column type`() {
        assertThrows(IllegalStateException::class.java) { ObjectTableGenerate.sqlTypeFor(ColumnTyping.file) }
    }
}
