export const DOCKER_PULL = `docker pull ghcr.io/nokimimo/homelab-project:v1.0.2`

export const DOCKER_RUN = `docker run -d --name homelab \\
  -p 80:80 \\
  -e POSTGRES_USER=user \\
  -e POSTGRES_PASSWORD=change-me \\
  -v homelab-data:/var/lib/postgresql/data \\
  -v ./modules:/app_root/modules:ro \\
  ghcr.io/nokimimo/homelab-project:v1.0.2`

export const DOCKER_COMPOSE_ALL_IN_ONE_YML = `# docker-compose.all-in-one.yml
services:
  homelab:
    build:
      context: .
      dockerfile: Dockerfile.all-in-one
    container_name: homelab-all-in-one
    ports:
      - "80:80"
    env_file:
      - .env.all-in-one
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./modules:/app_root/modules:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - JAVA_OPTS=-Doshi.os.windows.osRelease.path=/host/etc/os-release
    restart: unless-stopped

volumes:
  db-data:`

export const ENV_ALL_IN_ONE = `# .env.all-in-one
  POSTGRES_USER=user
  POSTGRES_PASSWORD=change-me
  POSTGRES_DB=homelab`

export const DOCKER_COMPOSE_SPLIT_YML = `# docker-compose.yml
services:
  homelab-backend:
    build: ./homelab-backend
    container_name: homelab-backend
    ports:
      - "8080:8080"
    depends_on:
      - homelab-db
    env_file:
      - .env.production
    volumes:
      - /proc:/host/proc:ro # read-only mount of proc for oshi : CPU and memory info
      - /sys:/host/sys:ro # read-only mount of sys for oshi : CPU and memory info
      - /etc/os-release:/host/etc/os-release:ro # read-only mount of os-release for oshi : OS info
      - //var/run/docker.sock:/var/run/docker.sock
      - .:/app_root:ro # read-only mount of the current dir for modules discovery
    environment:
      - JAVA_OPTS=-Doshi.os.windows.proc.path=/host/proc -Doshi.os.windows.sys.path=/host/sys -Doshi.os.windows.osRelease.path=/host/etc/os-release
    restart: unless-stopped
    networks:
      - homelab-network
      - db-network

  homelab-db:
    image: postgres:16-alpine
    container_name: homelab-db
    env_file:
      - .env.production
    environment:
      - POSTGRES_DB=homelab
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network
    restart: unless-stopped

  homelab-frontend:
    build: ./homelab-frontend
    container_name: homelab-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - homelab-network

networks:
  homelab-network:
    name: homelab-network
  db-network:
    name: db-network

volumes:
  db-data:`

export const ENV_PRODUCTION_EXAMPLE = `# .env.production
POSTGRES_USER=user
POSTGRES_PASSWORD=change-me
POSTGRES_DB=homelab
# hostname is the db service name from docker-compose.yml, not localhost
DB_URL=homelab-db:5432
HOMELAB_MODULES_SCAN_PATH=/app_root/modules`

export const BUILDER_REQUEST = `POST /api/admin/module-builder
Authorization: Bearer <token admin>

{
  "id": "tasks",
  "name": "Tâches",
  "description": "Gestionnaire de tâches simple.",
  "tables": [
    {
      "name": "tasks",
      "columns": [
        { "name": "title", "type": "string", "nullable": false },
        { "name": "done", "type": "boolean" }
      ],
      "enableFileStorage": false,
      "relations": [],
      "uniqueTogether": []
    }
  ],
  "params": []
}`

export const MANIFEST_MANUAL = `{
  "id": "tasks",
  "name": "Tâches",
  "version": "1.0.0",
  "description": "Gestionnaire de tâches simple.",
  "actions": [
    {
      "visual": "tasks.xml",
      "functions": [
        {
          "name": "createTask",
          "parameters": [{ "name": "title", "type": "NONE" }],
          "logic": [{ "type": "CREATE" }],
          "actUponObject": "tasks.xml"
        },
        {
          "name": "listTasks",
          "parameters": [],
          "logic": [{ "type": "LIST" }],
          "actUponObject": "tasks.xml"
        }
      ]
    }
  ],
  "page": "tasks_ui.json",
  "dataObjects": ["tasks.xml"],
  "uIFormat": "JSON",
  "permissions": ["read:tasks", "write:tasks", "delete:tasks"]
}`

export const TASKS_XML = `<tasks>
    <autoGenerated>
        <id/>
        <createdAt/>
        <updatedAt/>
    </autoGenerated>

    <col>
        <naming val="title"/>
        <typing val="string"/>
        <nullable val="false"/>
    </col>

    <col>
        <naming val="done"/>
        <typing val="boolean"/>
    </col>
</tasks>`

export const SERIE_XML = `<!-- serie.xml -->
<serie>
    <autoGenerated>
        <id/>
        <createdAt/>
        <updatedAt/>
    </autoGenerated>

    <col>
        <naming val="title"/>
        <typing val="String"/>
    </col>

    <!-- une série contient plusieurs groupes, un groupe n'appartient qu'à une série -->
    <linksTo>
        <targetObject>groups</targetObject>
        <cardinality>one-to-many</cardinality>
        <cascadeDelete>true</cascadeDelete>
        <cascadeUpdate>false</cascadeUpdate>
    </linksTo>
</serie>`

export const GROUPS_XML = `<!-- groups.xml -->
<groups>
    <autoGenerated>
        <id/>
        <createdAt/>
        <updatedAt/>
    </autoGenerated>

    <col>
        <naming val="index"/>
        <typing val="int"/>
    </col>

    <!-- un groupe peut contenir plusieurs contenus, un contenu appartient à un seul groupe -->
    <linksTo>
        <targetObject>groupContent</targetObject>
        <cardinality>one-to-many</cardinality>
        <cascadeDelete>true</cascadeDelete>
        <cascadeUpdate>false</cascadeUpdate>
    </linksTo>

    <constraints>
        <uniqueTogether name="uq_groups_serie_index">
            <field>serie_id</field>
            <field>index</field>
        </uniqueTogether>
    </constraints>
</groups>`

export const GROUPCONTENT_XML = `<!-- groupContent.xml -->
<groupContent>
    <autoGenerated>
        <id/>
        <createdAt/>
        <updatedAt/>
    </autoGenerated>

    <col>
        <naming val="index"/>
        <typing val="int"/>
    </col>

    <!-- un contenu pointe vers une seule photo (module externe "photos") -->
    <linksTo>
        <moduleName>photos</moduleName>
        <targetObject>photos</targetObject>
        <cardinality>many-to-one</cardinality>
        <cascadeDelete>true</cascadeDelete>
        <cascadeUpdate>false</cascadeUpdate>
    </linksTo>

    <constraints>
        <uniqueTogether name="uq_groups_content_index">
            <field>groups_id</field>
            <field>index</field>
        </uniqueTogether>
    </constraints>
</groupContent>`

export const UI_JSON_EXAMPLE = `{
  "page": {
    "id": "photos_page",
    "layout": "vertical",
    "bindings": {
      "list": "listPhotos",
      "upload": "addPhoto"
    },
    "state": { "fullscreenPhotoId": null },
    "components": [
      { "type": "Header", "props": { "title": "Stockage Photo" } },
      {
        "type": "FileUploadZone",
        "props": { "id": "photos-upload", "accept": "image/*" },
        "action": [
          { "action": "addPhoto", "method": "POST" },
          { "action": "listPhotos", "method": "POST" }
        ]
      },
      {
        "type": "List",
        "source": { "binding": "listPhotos", "method": "POST" },
        "item": {
          "type": "ListItem",
          "props": { "title": "{{file_name}}" },
          "defaultClick": {
            "action": "getPhoto",
            "method": "POST",
            "params": { "id": "{{id}}" },
            "then": { "setState": { "fullscreenPhotoId": "{{id}}" } }
          }
        }
      },
      {
        "type": "Modal",
        "visible": "{{fullscreenPhotoId != null}}",
        "content": {
          "type": "ImageViewer",
          "source": { "binding": "getPhoto", "method": "POST" },
          "params": { "id": "{{fullscreenPhotoId}}" }
        }
      }
    ]
  }
}`

export const SDK_GRADLE = `repositories {
    mavenCentral()
    maven {
        // TODO: URL du repository (GitHub Packages / Maven) --- publication à venir
        url = uri("https://TODO-add-repository-url")
    }
}

dependencies {
    implementation("com.homelab:homelab-sdk:0.0.3")
}`
