package com.homelab.core.parser

import com.homelab.core.model.data.AutoGeneratedColumn
import com.homelab.core.model.data.AutoGeneratedType
import com.homelab.core.model.data.TableDefinition
import com.homelab.core.model.data.ColumnDefinition
import org.w3c.dom.Node
import javax.xml.parsers.DocumentBuilderFactory
import org.w3c.dom.Element

class ModuleDataObjectParser : Parser<TableDefinition> {
    override fun parse(element: Element): TableDefinition {
        val name = element.tagName

        val columns = mutableListOf<ColumnDefinition>()
        val autoGeneratedColumns = mutableListOf<AutoGeneratedColumn>()

        val childNodes = element.childNodes
        for (i in 0 until childNodes.length) {
            val node = childNodes.item(i)
            if (node.nodeType == Node.ELEMENT_NODE) {
                val childElement = node as Element
                when (DataTag.valueOf(childElement.tagName.uppercase())) {
                    DataTag.AUTOGENERATED -> {
                        val autoGenChildren = childElement.childNodes
//                        println("Found auto-generated columns: ${autoGenChildren.length}")
                        for (j in 0 until autoGenChildren.length) {
                            val autoGenNode = autoGenChildren.item(j)
                            if (autoGenNode.nodeType == Node.ELEMENT_NODE) {
                                val autoGenElement = autoGenNode as Element
//                                println("Auto-generated column: ${autoGenElement.tagName}")
                                when (DataTag.valueOf(autoGenElement.tagName.uppercase())) {
                                    DataTag.ID -> autoGeneratedColumns.add(AutoGeneratedColumn(AutoGeneratedType.ID))
                                    DataTag.CREATEDAT -> autoGeneratedColumns.add(AutoGeneratedColumn(AutoGeneratedType.CREATED_AT))
                                    DataTag.UPDATEDAT -> autoGeneratedColumns.add(AutoGeneratedColumn(AutoGeneratedType.UPDATED_AT))
                                    DataTag.FILE -> autoGeneratedColumns.add(AutoGeneratedColumn(AutoGeneratedType.FILE))
                                    else -> {}
                                }
                            }
                        }
                    }
                    DataTag.COL -> {
                        val name = childElement.getElementsByTagName(DataTag.NAMING.name.lowercase()).item(0).attributes.getNamedItem("val").nodeValue
                        val type = childElement.getElementsByTagName(DataTag.TYPING.name.lowercase()).item(0).attributes.getNamedItem("val").nodeValue
                        val unique = childElement.getElementsByTagName(DataTag.UNIQUE.name.lowercase()).item(0)?.attributes?.getNamedItem("val")?.nodeValue == "True"
                        val nullable = childElement.getElementsByTagName(DataTag.NULLABLE.name.lowercase()).item(0)?.attributes?.getNamedItem("val")?.nodeValue != "False"
                        val regex = childElement.getElementsByTagName(DataTag.REGEX.name.lowercase()).item(0)?.attributes?.getNamedItem("val")?.nodeValue

//                        println("Adding column: name=$name, type=$type, unique=$unique, nullable=$nullable, regex=$regex") // Debug log for column details
                        columns.add(ColumnDefinition(name, type, unique, nullable, regex))
                    }
                    else -> {}
                }
            }
        }

        return TableDefinition(name, columns, autoGeneratedColumns)
    }

    companion object {
        fun parseFromXml(xml: String): TableDefinition {
            val factory = DocumentBuilderFactory.newInstance()
            val builder = factory.newDocumentBuilder()
            val document = builder.parse(xml.byteInputStream())
            val root = document.documentElement
            return ModuleDataObjectParser().parse(root)
        }
    }
}
