package com.homelab.core.parser

import com.homelab.core.helper.AppLogger
import com.homelab.core.service.AppletService
import org.w3c.dom.Node
import javax.xml.parsers.DocumentBuilderFactory
import org.w3c.dom.Element
import com.homelab.sdk.data.*

class ModuleDataObjectParser : Parser<TableDefinition> {
    private val log = AppLogger.loggerFor(AppletService::class)

    override fun parse(element: Element, moduleId: String?): TableDefinition {
        // Root tag may be the actual table name (e.g. <photos>) or a generic wrapper like <object>
        var name = element.tagName
        if (name.equals("object", ignoreCase = true) || name.equals("table", ignoreCase = true)) {
            // try to read a naming child if present
            val namingNode = element.getElementsByTagName("naming").item(0) as? Element
            val namingVal = namingNode?.attributes?.getNamedItem("val")?.nodeValue
            if (!namingVal.isNullOrBlank()) {
                name = namingVal
            }
        }

        val columns = mutableListOf<ColumnDefinition>()
        val autoGeneratedColumns = mutableListOf<AutoGeneratedColumn>()
        val relations = mutableListOf<RelationDefinition>()

        val childNodes = element.childNodes



        for (i in 0 until childNodes.length) {
            val node = childNodes.item(i)
            if (node.nodeType == Node.ELEMENT_NODE) {
                val childElement = node as Element
                val tag = childElement.tagName
                try {
                    when (tag.lowercase()) {
                        "autogenerated", "auto-generated", "autogen" -> {
                            val autoGenChildren = childElement.childNodes
                            for (j in 0 until autoGenChildren.length) {
                                val autoGenNode = autoGenChildren.item(j)
                                if (autoGenNode.nodeType == Node.ELEMENT_NODE) {
                                    val autoGenElement = autoGenNode as Element
                                    when (autoGenElement.tagName.lowercase()) {
                                        "id" -> autoGeneratedColumns.add(AutoGeneratedColumn(AutoGeneratedType.ID))
                                        "createdat", "created_at", "created-at", "created" -> autoGeneratedColumns.add(AutoGeneratedColumn(AutoGeneratedType.CREATED_AT))
                                        "updatedat", "updated_at", "updated-at", "updated" -> autoGeneratedColumns.add(AutoGeneratedColumn(AutoGeneratedType.UPDATED_AT))
                                        "file" -> autoGeneratedColumns.add(AutoGeneratedColumn(AutoGeneratedType.FILE))
                                        else -> println("[ModuleDataObjectParser] Unknown autogenerated child tag: ${autoGenElement.tagName}")
                                    }
                                }
                            }
                        }
                        //TODO: keep val check or use textContent?
                        "col", "column" -> {
                            // safe extraction of child fields
                            val nameNode = childElement.getElementsByTagName("naming").item(0) as? Element
                            val typeNode = childElement.getElementsByTagName("typing").item(0) as? Element
                            val uniqueNode = childElement.getElementsByTagName("unique").item(0) as? Element
                            val nullableNode = childElement.getElementsByTagName("nullable").item(0) as? Element
                            val regexNode = childElement.getElementsByTagName("regex").item(0) as? Element

                            val colName = nameNode?.attributes?.getNamedItem("val")?.nodeValue ?: run {
                                log.warn("[ModuleDataObjectParser] Missing naming for column element; skipping column: ${childElement.tagName}")
                                null
                            }
                            val colType = DataMapper.mapToColumnTyping(typeNode?.attributes?.getNamedItem("val")?.nodeValue ?: "string")
                            val unique = uniqueNode?.attributes?.getNamedItem("val")?.nodeValue?.lowercase() == "true"
                            val nullable = nullableNode?.attributes?.getNamedItem("val")?.nodeValue?.lowercase() != "false"
                            val regex = regexNode?.attributes?.getNamedItem("val")?.nodeValue

                            if (colName != null) {
                                columns.add(ColumnDefinition(colName, colType, unique, nullable, regex))
                            }
                        }
                        "linksto" -> {
                            var moduleName = childElement.getElementsByTagName("moduleName").item(0)?.textContent?.trim()
                            //println("[ModuleDataObjectParser] Parsing linksto relation, found moduleName: $moduleName and moduleId: $moduleId")
                            if (moduleName == null && moduleId != null) {
                                // si pas présent alors c'est dans le meme module
                                moduleName = moduleId
                            }else if(moduleName == null)
                                 throw IllegalArgumentException("moduleName is required for linksto relation when moduleId is not provided in parse()")

                            val dataObject = childElement.getElementsByTagName("targetObject").item(0)?.textContent?.trim()
                            val cardinalityText = childElement.getElementsByTagName("cardinality").item(0)?.textContent?.trim()
                            val cascadeDelete = childElement.getElementsByTagName("cascadeDelete").item(0)?.textContent?.trim()?.toBoolean() ?: false
                            val cascadeUpdate = childElement.getElementsByTagName("cascadeUpdate").item(0)?.textContent?.trim()?.toBoolean() ?: false

                            if (
                                dataObject != null && cardinalityText != null
                            ) {
                                val cardinality = when(cardinalityText.lowercase()) {
                                    "one-to-one" -> Cardinality.ONE_TO_ONE
                                    "one-to-many" -> Cardinality.ONE_TO_MANY
                                    "many-to-one" -> Cardinality.MANY_TO_ONE
                                    "many-to-many" -> Cardinality.MANY_TO_MANY
                                    else -> throw IllegalArgumentException(
                                        "Unknown cardinality: $cardinalityText"
                                    )
                                }

                                relations.add(
                                    RelationDefinition(
                                        moduleName, // Target module name that holds the remote table
                                        dataObject, // target object name in the remote module
                                        cardinality,
                                        cascadeDelete,
                                        cascadeUpdate,
                                    )
                                )
                            }
                        }
                        else -> {
                            // Unknown/irrelevant tag: log for debugging but continue
                            log.warn("[ModuleDataObjectParser] Skipping unknown child tag: $tag in table: $name")
                        }
                    }
                } catch (e: Exception) {
                    log.error("[ModuleDataObjectParser] Exception while parsing child tag '$tag' in table '$name': ${e.message}", e)
                }
            }
        }

        return TableDefinition(name, columns, autoGeneratedColumns, relations)
    }

    companion object {
        fun parseFromXml(xml: String, moduleId: String?): TableDefinition {
            val factory = DocumentBuilderFactory.newInstance()
            val builder = factory.newDocumentBuilder()
            val document = builder.parse(xml.byteInputStream())
            val root = document.documentElement
            return ModuleDataObjectParser().parse(root, moduleId)
        }
    }

}
