-- Baseline migration: captures the schema as it existed under Hibernate's
-- ddl-auto=update before Flyway was introduced. Only covers the core,
-- JPA-entity-backed tables (public schema). Module data tables (e.g. the
-- photos/reader/weather schemas) are created dynamically by the module
-- install process and are intentionally out of Flyway's scope.
--
-- On a fresh database this script creates the tables. On an existing
-- database, Flyway's baseline-on-migrate config causes this version to be
-- recorded as already applied without being executed.

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    is_admin boolean NOT NULL,
    name character varying(255),
    password_hash character varying(2048),
    public_key character varying(2048),
    must_reset_password boolean DEFAULT false NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email)
);

CREATE TABLE user_permissions (
    user_id bigint NOT NULL,
    permission character varying(255),
    CONSTRAINT fkkowxl8b2bngrxd1gafh13005u FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE login_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description character varying(500),
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT login_settings_pkey PRIMARY KEY (id)
);

CREATE TABLE password_reset_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    processed_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    CONSTRAINT password_reset_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE recovery_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code_hash character varying(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT recovery_codes_pkey PRIMARY KEY (id)
);

CREATE TABLE signup_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255),
    password_hash character varying(2048),
    processed_at timestamp(6) without time zone,
    public_key character varying(2048),
    status character varying(255) NOT NULL,
    CONSTRAINT signup_requests_pkey PRIMARY KEY (id)
);
