-- Replaces the per-user granted-permission model with per-module write/delete
-- admin-only toggles. Module invocation authorization is now: reads are open
-- to any authenticated user; writes/deletes are open by default unless an
-- admin flips the corresponding toggle for that module.

CREATE TABLE module_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    module_id character varying(255) NOT NULL,
    write_admin_only boolean NOT NULL DEFAULT false,
    delete_admin_only boolean NOT NULL DEFAULT false,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT module_settings_pkey PRIMARY KEY (id),
    CONSTRAINT uk_module_settings_module_id UNIQUE (module_id)
);

DROP TABLE user_permissions;
