services:
  homelab-backend:
    build: ./homelab-backend
    container_name: homelab-backend
    ports:
      - "8080:8080"
    depends_on:
      - homelab-db
    env_file:
      - .env.production
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - //var/run/docker.sock:/var/run/docker.sock
      - .:/app_root:ro
    environment:
      - JAVA_OPTS=-Doshi.os.windows.proc.path=/host/proc -Doshi.os.windows.sys.path=/host/sys
    restart: unless-stopped
    networks:
      - homelab-network
      - db-network

  homelab-db:
    image: postgres:16-alpine
    container_name: homelab-db
    env_file:
      - .env.production
    environment:
      - POSTGRES_DB=homelab
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network
    restart: unless-stopped

  homelab-frontend:
    build: ./homelab-frontend
    container_name: homelab-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - homelab-network

networks:
  homelab-network:
    name: homelab-network
  db-network:
    name: db-network

volumes:
  db-data:
