import type { ReactNode } from 'react'
import Badge from '../../components/Badge'
import CodeBlock from '../../components/CodeBlock'
import FieldTable from '../../components/FieldTable'
import { SDK_GRADLE } from '../../data/snippets'
import { useLanguage, type Lang } from '../../i18n/LanguageContext'

const TEXT: Record<
  Lang,
  {
    title: string
    intro: ReactNode
    depsTitle: string
    depsBadge: string
    depsNote: ReactNode
    packagesTitle: string
    packagesColumns: string[]
    packagesRows: (string | ReactNode)[][]
  }
> = {
  fr: {
    title: 'SDK',
    intro: (
      <>
        <code>homelab-sdk</code> fournit les types Kotlin partagés pour écrire
        la logique d'un module côté backend (schémas, relations, filtres,
        déclarations d'actions et de paramètres).
      </>
    ),
    depsTitle: 'Ajouter la dépendance',
    depsBadge: 'URL à venir',
    depsNote: (
      <>
        Le SDK n'est pas encore publié sur un repository public --- l'URL
        ci-dessous sera mise à jour à la publication. En attendant, il est
        disponible en local via{' '}
        <code>./gradlew :homelab-sdk:publishLocal</code>.
      </>
    ),
    packagesTitle: 'Packages principaux',
    packagesColumns: ['Package', 'Contenu'],
    packagesRows: [
      [
        'com.homelab.sdk.data',
        'TableDefinition, ColumnDefinition, ColumnTyping, Cardinality, RelationDefinition, UniqueTogetherDefinition, AutoGeneratedColumn',
      ],
      [
        'com.homelab.sdk.filter',
        <>
          FilterOperator, FilterSpec --- filtres de requête (<code>EQUAL</code>,{' '}
          <code>GREATER</code>, <code>LESS</code>, <code>GREATER_EQUAL</code>,{' '}
          <code>LESS_EQUAL</code>)
        </>,
      ],
      [
        'com.homelab.sdk.module.action',
        'ModuleActionDeclaration, ModuleActionParameter, ModuleActionParameterType --- déclaration des fonctions exposées par un module',
      ],
      [
        'com.homelab.sdk.module.param',
        'ModuleParamDeclaration, ModuleParamsConfig --- paramètres configurables exposés dans le dashboard',
      ],
      [
        'com.homelab.sdk.plugin / context',
        'LogicPlugin, PluginContext --- point d’entrée pour la logique custom d’un module',
      ],
      [
        'com.homelab.sdk.helper',
        'AppLogger, Formater, PathRules, FilterHelpers, ValidationRules --- utilitaires partagés',
      ],
    ],
  },
  en: {
    title: 'SDK',
    intro: (
      <>
        <code>homelab-sdk</code> provides the shared Kotlin types for writing
        a module's backend logic (schemas, relations, filters, action and
        parameter declarations).
      </>
    ),
    depsTitle: 'Add the dependency',
    depsBadge: 'URL coming soon',
    depsNote: (
      <>
        The SDK isn't published on a public repository yet --- the URL below
        will be updated once it is. In the meantime, it's available locally
        via <code>./gradlew :homelab-sdk:publishLocal</code>.
      </>
    ),
    packagesTitle: 'Main packages',
    packagesColumns: ['Package', 'Contents'],
    packagesRows: [
      [
        'com.homelab.sdk.data',
        'TableDefinition, ColumnDefinition, ColumnTyping, Cardinality, RelationDefinition, UniqueTogetherDefinition, AutoGeneratedColumn',
      ],
      [
        'com.homelab.sdk.filter',
        <>
          FilterOperator, FilterSpec --- query filters (<code>EQUAL</code>,{' '}
          <code>GREATER</code>, <code>LESS</code>, <code>GREATER_EQUAL</code>,{' '}
          <code>LESS_EQUAL</code>)
        </>,
      ],
      [
        'com.homelab.sdk.module.action',
        'ModuleActionDeclaration, ModuleActionParameter, ModuleActionParameterType --- declares the functions a module exposes',
      ],
      [
        'com.homelab.sdk.module.param',
        'ModuleParamDeclaration, ModuleParamsConfig --- configurable parameters exposed on the dashboard',
      ],
      [
        'com.homelab.sdk.plugin / context',
        'LogicPlugin, PluginContext --- entry point for a module’s custom logic',
      ],
      [
        'com.homelab.sdk.helper',
        'AppLogger, Formater, PathRules, FilterHelpers, ValidationRules --- shared utilities',
      ],
    ],
  },
}

function SdkGuide() {
  const { lang } = useLanguage()
  const t = TEXT[lang]

  return (
    <div>
      <h1 className="text-4xl font-bold mb-6">{t.title}</h1>

      <p className="text-base-content/70 max-w-2xl">{t.intro}</p>

      <h2 className="text-2xl font-semibold mt-8 mb-2">{t.depsTitle}</h2>
      <Badge tone="todo">{t.depsBadge}</Badge>
      <p className="text-base-content/70 max-w-2xl mt-3">{t.depsNote}</p>
      <CodeBlock lang="kotlin">{SDK_GRADLE}</CodeBlock>

      <h2 className="text-2xl font-semibold mt-8 mb-2">{t.packagesTitle}</h2>
      <FieldTable columns={t.packagesColumns} rows={t.packagesRows} />
    </div>
  )
}

export default SdkGuide
