package com.homelab.core.service.module

import com.homelab.sdk.data.Cardinality
import com.homelab.sdk.data.ColumnDefinition
import com.homelab.sdk.data.ColumnTyping
import com.homelab.sdk.data.RelationDefinition
import com.homelab.sdk.data.TableDefinition
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Test
import org.mockito.Mockito.mock
import org.mockito.Mockito.never
import org.mockito.Mockito.verify
import org.mockito.Mockito.`when`
import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.ResultSet
import java.sql.ResultSetMetaData

class RelationLoaderTest {

    private val loader = RelationLoader()

    private fun tableWith(relation: RelationDefinition) = TableDefinition(
        name = "albums",
        columns = listOf(ColumnDefinition("id", ColumnTyping.string)),
        autoGeneratedColumns = emptyList(),
        relations = listOf(relation)
    )

    @Test
    fun `loadRelations sets an empty list for MANY_TO_MANY when there are no base ids and never touches the connection`() {
        val connection = mock(Connection::class.java)
        val definition = tableWith(RelationDefinition("photos_mod", "photos", Cardinality.MANY_TO_MANY))
        val rows = listOf(mapOf("id" to null, "title" to "empty"))

        val result = loader.loadRelations(connection, "albums_mod", "albums", definition, rows)

        assertEquals(emptyList<Any>(), result.first()["photos"])
        verify(connection, never()).prepareStatement(org.mockito.ArgumentMatchers.anyString())
    }

    @Test
    fun `loadRelations sets an empty list for ONE_TO_MANY when there are no base ids`() {
        val connection = mock(Connection::class.java)
        val definition = tableWith(RelationDefinition("photos_mod", "photos", Cardinality.ONE_TO_MANY))
        val rows = listOf(mapOf("id" to null))

        val result = loader.loadRelations(connection, "albums_mod", "albums", definition, rows)

        assertEquals(emptyList<Any>(), result.first()["photos"])
        verify(connection, never()).prepareStatement(org.mockito.ArgumentMatchers.anyString())
    }

    @Test
    fun `loadRelations sets null for MANY_TO_ONE and ONE_TO_ONE when the foreign key is absent`() {
        val connectionManyToOne = mock(Connection::class.java)
        val manyToOneDef = tableWith(RelationDefinition("photos_mod", "photos", Cardinality.MANY_TO_ONE))
        val resultManyToOne = loader.loadRelations(connectionManyToOne, "albums_mod", "albums", manyToOneDef, listOf(mapOf("id" to "a1")))
        assertNull(resultManyToOne.first()["photos"])
        verify(connectionManyToOne, never()).prepareStatement(org.mockito.ArgumentMatchers.anyString())

        val connectionOneToOne = mock(Connection::class.java)
        val oneToOneDef = tableWith(RelationDefinition("photos_mod", "photos", Cardinality.ONE_TO_ONE))
        val resultOneToOne = loader.loadRelations(connectionOneToOne, "albums_mod", "albums", oneToOneDef, listOf(mapOf("id" to "a1")))
        assertNull(resultOneToOne.first()["photos"])
    }

    @Test
    fun `loadRelations deduplicates repeated MANY_TO_ONE foreign keys into a single query`() {
        val connection = mock(Connection::class.java)
        val statement = mock(PreparedStatement::class.java)
        val resultSet = mock(ResultSet::class.java)
        val metaData = mock(ResultSetMetaData::class.java)
        `when`(connection.prepareStatement(org.mockito.ArgumentMatchers.anyString())).thenReturn(statement)
        `when`(statement.executeQuery()).thenReturn(resultSet)
        `when`(resultSet.metaData).thenReturn(metaData)
        `when`(metaData.columnCount).thenReturn(2)
        `when`(metaData.getColumnLabel(1)).thenReturn("id")
        `when`(metaData.getColumnLabel(2)).thenReturn("name")
        `when`(resultSet.next()).thenReturn(true, false)
        `when`(resultSet.getObject(1)).thenReturn("city-1")
        `when`(resultSet.getObject(2)).thenReturn("Paris")

        val definition = tableWith(RelationDefinition("weather_mod", "cities", Cardinality.MANY_TO_ONE))
        val rows = listOf(mapOf("id" to "a1", "cities_id" to "city-1"), mapOf("id" to "a2", "cities_id" to "city-1"))

        val result = loader.loadRelations(connection, "albums_mod", "albums", definition, rows)

        assertEquals(mapOf("id" to "city-1", "name" to "Paris"), result[0]["cities"])
        assertEquals(mapOf("id" to "city-1", "name" to "Paris"), result[1]["cities"])
        // Both rows share the same FK value, so only one row should have actually been fetched.
        verify(connection).prepareStatement(org.mockito.ArgumentMatchers.anyString())
    }
}
