package com.homelab.core.service.module

import com.homelab.core.config.ObjectDefinitionMemory
import com.homelab.core.service.module.sql.ObjectRelationUpdater.Companion.updateRelations
import com.homelab.core.service.module.sql.ObjectTableGenerate
import com.homelab.core.service.module.sql.SQLHelper.Companion.convertFilterValue
import com.homelab.core.service.module.sql.SQLHelper.Companion.dataTypeConversion
import com.homelab.sdk.data.AutoGeneratedType
import com.homelab.sdk.data.TableDefinition
import com.homelab.sdk.data.ModuleDatabaseService as ModuleDatabaseServiceInterface
import org.springframework.stereotype.Service
import javax.sql.DataSource
import com.homelab.core.service.module.sql.SQLHelper.Companion.safeSqlName
import com.homelab.core.exception.BadRequestException
import com.homelab.core.exception.ForbiddenException
import com.homelab.core.exception.NotFoundException
import com.homelab.core.exception.PersistenceException
import com.homelab.core.helper.AppLogger
import com.homelab.core.service.AppletService

@Service
class ModuleDatabaseService(
    private val dataSource: DataSource,
    private val objectDefinitionMemory: ObjectDefinitionMemory
) : ModuleDatabaseServiceInterface {
    companion object {
        // "magic number" for now, will use module parameter when implemented
        private const val MAX_RELATION_CACHE_KB = 1024
    }
    private val log = AppLogger.loggerFor(AppletService::class)

    private val relationLoader = RelationLoader(MAX_RELATION_CACHE_KB)

    override fun ensureModuleDatabaseReady(moduleId: String): Boolean {
        val schemaName = safeSqlName(moduleId)

        return try {
            dataSource.connection.use { connection ->
                connection.autoCommit = true

                val exists = connection.prepareStatement(
                    "SELECT 1 FROM information_schema.schemata WHERE schema_name = ?"
                ).use { stmt ->
                    stmt.setString(1, schemaName)
                    stmt.executeQuery().use { rs -> rs.next() }
                }

                if (!exists) {
                    connection.createStatement().use { st ->
                        st.execute("""CREATE SCHEMA "$schemaName"""")
                    }
                    log.info("Created module schema '$schemaName'")
                }
                true
            }
        } catch (e: Exception) {
            log.error("Failed ensuring module schema '$schemaName': ${e.message}", e)
            false
        }
    }

    override fun setUpModuleDataObject(moduleId: String, objectsDefinition: TableDefinition): Boolean {
        val schemaName = safeSqlName(moduleId)
        val tableName = safeSqlName(objectsDefinition.name)
        log.debug("Setting up module data object for moduleId: $moduleId, tableName: $tableName with definition: $objectsDefinition")
        val sql = ObjectTableGenerate.buildCreateTableSql(schemaName, tableName, objectsDefinition)
        log.debug("Setting up table with SQL: \n$sql")
        return try {
            dataSource.connection.use { connection ->
                connection.createStatement().use { statement ->
                    // TODO: we should ideally check if the table exists and matches the definition,
                    //  but i don't want to do reconciliation rn
                    statement.execute(sql)
                }
            }
            objectDefinitionMemory.put(moduleId, objectsDefinition)

            true
        } catch (e: Exception) {
            log.error("Failed setting up table '$schemaName.$tableName': ${e.message}", e)
            false
        }
    }

    override fun setUpModuleDataObjectRelations(moduleId: String, objectsDefinition: TableDefinition): Boolean {
        val schemaName = safeSqlName(moduleId)
        val tableName = safeSqlName(objectsDefinition.name)
        for (relation in objectsDefinition.relations) {
            val sql = updateRelations(schemaName,tableName, relation)
            try {
                dataSource.connection.use { connection ->
                    connection.createStatement().use { statement ->
                        // TODO: we should ideally check if the table exists and matches the definition,
                        //  but i don't want to do reconciliation rn X2
                        statement.execute(sql)
                    }
                }

            } catch (e: Exception) {
                log.error("Failed setting up relations for table '$schemaName.$tableName': ${e.message}", e)
                // Not returning false here because the main table was created successfully,
                // and relation setup can be retried later without affecting the main object availability
            }
        }
        return true
    }

    override fun insertRow(moduleId: String, tableName: String, item: Map<String, Any?>, definition: TableDefinition): Boolean {
        val schemaName = safeSqlName(moduleId)
        val tblName = safeSqlName(tableName)

        try {
            dataSource.connection.use { connection ->
                val cols = mutableListOf<String>()
                val values = mutableListOf<Any?>()

                val autoTypes = definition.autoGeneratedColumns.map { it.type }.toSet()

                fun addColumn(name: String, value: Any?) {
                    cols.add("\"${safeSqlName(name)}\"")
                    values.add(value)
                }

                for (colDef in definition.columns) {
                    val key = colDef.name
                    if (item.containsKey(key)) {
                        val raw0 = item[key]
                        val raw = if (raw0 is Pair<*, *>) raw0.first else raw0
                        val converted: Any? = dataTypeConversion(colDef.type, raw)
                        addColumn(colDef.name, converted)
                    }
                }

                if (AutoGeneratedType.FILE in autoTypes) {
                    if (item.containsKey("file")) {
                        val v0 = item["file"]
                        val v = if (v0 is Pair<*, *>) v0.first else v0
                        when (v) {
                            is Map<*, *> -> {
                                val pathRaw = v["file"] ?: v["filePath"]
                                val fnameRaw = v["file_name"] ?: v["fileName"] ?: v["originalFilename"]
                                val path = if (pathRaw is Pair<*, *>) pathRaw.first?.toString() else pathRaw?.toString()
                                val fname = if (fnameRaw is Pair<*, *>) fnameRaw.first?.toString() else fnameRaw?.toString()
                                if (path != null) addColumn("file", path)
                                if (fname != null) addColumn("file_name", fname)
                            }
                            is String -> addColumn("file", v)
                            else -> {}
                        }
                    }
                    if (item.containsKey("filePath") && cols.none { it.contains("file") }) {
                        val fp0 = item["filePath"]
                        val fp = if (fp0 is Pair<*, *>) fp0.first?.toString() else fp0?.toString()
                        addColumn("file", fp)
                    }
                    if (item.containsKey("fileName") && cols.none { it.contains("file_name") }) {
                        val fn0 = item["fileName"]
                        val fn = if (fn0 is Pair<*, *>) fn0.first?.toString() else fn0?.toString()
                        addColumn("file_name", fn)
                    }
                }

                // Include any foreign-key-like fields provided in the item that are not declared
                // in the TableDefinition.columns (eg. fk_id). This allows callers to pass
                // relation FK values without having to duplicate FK columns in the object definition.
                for ((k, v) in item) {
                    if (!k.endsWith("_id", true)) continue
                    // already added?
                    val safe = "\"${safeSqlName(k)}\""
                    if (cols.any { it == safe }) continue

                    val raw0 = v
                    val raw = if (raw0 is Pair<*, *>) raw0.first else raw0
                    // Try to convert (UUID, number, date...) using the existing helper
                    val converted = convertFilterValue(raw)
                    addColumn(k, converted)
                }



                // check for relation and FK columns that may not be in the definition.columns list but are needed for insertion
                val sql = if (cols.isEmpty()) {
                    "INSERT INTO \"$schemaName\".\"$tblName\" DEFAULT VALUES"
                } else {
                    val placeholders = cols.joinToString(",") { "?" }
                    "INSERT INTO \"$schemaName\".\"$tblName\" (${cols.joinToString(",")}) VALUES ($placeholders)"
                }
                log.info("Inserting row into \"$schemaName\".\"$tblName\": $sql with values: ${values.joinToString(", ")}")

                connection.prepareStatement(sql).use { stmt ->
                    for (i in values.indices) {
                        stmt.setObject(i + 1, values[i])
                    }
                    val updated = stmt.executeUpdate()
                    return updated > 0
                }
            }
        } catch (e: Exception) {
            val msg = "Failed inserting row into \"$schemaName\".\"$tblName\": ${e.message}"
            log.error(msg, e)
            if (e is java.sql.SQLException) {
                val sqlState = e.sqlState ?: ""
                when {
                    // Integrity constraint violation (e.g. not null, foreign key, unique)
                    sqlState.startsWith("23") -> throw BadRequestException(msg, e)
                    // Undefined table / invalid catalog / undefined schema
                    sqlState == "42P01" || sqlState == "3D000" || sqlState == "3F000" -> throw NotFoundException(msg, e)
                    // Authorization / privilege issues
                    sqlState.startsWith("28") || sqlState == "42501" -> throw ForbiddenException(msg, e)
                    else -> throw PersistenceException(msg, e)
                }
            }
            throw PersistenceException(msg, e)
        }
    }

    override fun queryRows(moduleId: String, tableName: String, filters: Map<String, Any?>): List<Map<String, Any?>> {
        val schemaName = safeSqlName(moduleId)
        val tblName = safeSqlName(tableName)
        val results = mutableListOf<Map<String, Any?>>()

        val tableDefinition = objectDefinitionMemory.getDefinition(moduleId, tableName)
        if (tableDefinition == null) {
            log.warn("queryRows: tableDefinition not found for moduleId: $moduleId, tableName: $tableName")
            return results
        }
        try {
            dataSource.connection.use { connection ->
                val (where, params) = buildWhereClause(filters)
                val sql = "SELECT * FROM \"$schemaName\".\"$tblName\"$where"
                log.debug("Querying rows from \"$schemaName\".\"$tblName\": $sql with values: ${params.joinToString(", ")}")

                val baseRows = mutableListOf<Map<String, Any?>>()

                connection.prepareStatement(sql).use { stmt ->
                    for (i in params.indices) stmt.setObject(i + 1, params[i])
                    stmt.executeQuery().use { rs ->
                        val md = rs.metaData
                        while (rs.next()) {
                            val row = mutableMapOf<String, Any?>()
                            for (i in 1..md.columnCount) {
                                val colName = md.getColumnLabel(i)
                                row[colName] = rs.getObject(i)
                            }
                            baseRows.add(row)
                        }
                    }
                }

                return baseRows
            }
        } catch (e: Exception) {
            log.error("Failed querying rows from \"$schemaName\".\"$tblName\": ${e.message}", e)
        }
        return results
    }

    override fun loadRelationsForRows(moduleId: String, tableName: String, rows: List<Map<String, Any?>>): List<Map<String, Any?>> {
        if (rows.isEmpty()) return rows

        val tableDefinition = objectDefinitionMemory.getDefinition(moduleId, tableName)
            ?: return rows

        val schemaName = safeSqlName(moduleId)
        val tblName = safeSqlName(tableName)

        try {
            dataSource.connection.use { connection ->
                return relationLoader.loadRelations(connection, schemaName, tblName, tableDefinition, rows)
            }
        } catch (e: Exception) {
            log.error("Failed loading relations for \"$schemaName\".\"$tblName\": ${e.message}", e)
        }

        return rows
    }

    override fun deleteRowsByFilters(moduleId: String, tableName: String, filters: Map<String, Any?>): Int {
        val schemaName = safeSqlName(moduleId)
        val tblName = safeSqlName(tableName)
        try {
            dataSource.connection.use { connection ->
                val (where, params) = buildWhereClause(filters)
                val sql = "DELETE FROM \"$schemaName\".\"$tblName\"$where"
                connection.prepareStatement(sql).use { stmt ->
                    for (i in params.indices) stmt.setObject(i + 1, params[i])
                    return stmt.executeUpdate()
                }
            }
        } catch (e: Exception) {
            log.error("Failed deleting rows from \"$schemaName\".\"$tblName\": ${e.message}", e)
        }
        return 0
    }

    override fun updateRows(

        moduleId: String,
        tableName: String,
        filters: Map<String, Any?>,
        updateMap: Map<String, Any?>
    ): Int {
        val schemaName = safeSqlName(moduleId)
        val tblName = safeSqlName(tableName)

        if (updateMap.isEmpty()) {
            log.warn("updateRows: updateMap is empty for moduleId: $moduleId, tableName: $tableName")
            return 0
        }

        try {
            dataSource.connection.use { connection ->
                val setClauses = mutableListOf<String>()
                val setParams = mutableListOf<Any?>()

                for ((k, v) in updateMap) {
                    val col = safeSqlName(k)
                    setClauses.add("\"$col\" = ?")
                    setParams.add(v)
                }

                val (where, whereParams) = buildWhereClause(filters)
                if (where.isEmpty()) {
                    log.warn("updateRows: no filters provided for moduleId: $moduleId, tableName: $tableName. Skipping update for safety.")
                    return 0
                }

                val setClause = setClauses.joinToString(", ")
                val sql = "UPDATE \"$schemaName\".\"$tblName\" SET $setClause$where"

                connection.prepareStatement(sql).use { stmt ->
                    var paramIndex = 1
                    for (param in setParams) stmt.setObject(paramIndex++, param)
                    for (param in whereParams) stmt.setObject(paramIndex++, param)
                    return stmt.executeUpdate()
                }
            }
        } catch (e: Exception) {
            log.error("Failed updating rows in \"$schemaName\".\"$tblName\": ${e.message}", e)
            e.printStackTrace()
        }
        return 0
    }

    private fun buildWhereClause(filters: Map<String, Any?>): Pair<String, List<Any?>> {
        if (filters.isEmpty()) return Pair("", emptyList())
        val whereClauses = mutableListOf<String>()
        val params = mutableListOf<Any?>()

        for ((k, v) in filters) {
            val col = safeSqlName(k)

            var operatorSql = "="
            var rawValue: Any? = v

            if (v is Pair<*, *>) {
                rawValue = v.first
                val op = v.second
                if (op is com.homelab.sdk.module.action.ModuleActionParameterType) {
                    operatorSql = when (op) {
                        com.homelab.sdk.module.action.ModuleActionParameterType.EQUAL -> "="
                        com.homelab.sdk.module.action.ModuleActionParameterType.GREATER -> ">"
                        com.homelab.sdk.module.action.ModuleActionParameterType.LESS -> "<"
                        com.homelab.sdk.module.action.ModuleActionParameterType.GREATER_EQUAL -> ">="
                        com.homelab.sdk.module.action.ModuleActionParameterType.LESS_EQUAL -> "<="
                        com.homelab.sdk.module.action.ModuleActionParameterType.NONE -> { rawValue = null; "=" }
                    }
                }
            }

            if (rawValue == null) continue

            if (rawValue is Collection<*>) {
                val items = rawValue.map { convertFilterValue(it) }
                if (items.isEmpty()) continue
                val placeholders = items.joinToString(",") { "?" }
                whereClauses.add("\"$col\" IN ($placeholders)")
                params.addAll(items)
                continue
            }

            whereClauses.add("\"$col\" $operatorSql ?")
            params.add(convertFilterValue(rawValue))
        }

        val where = if (whereClauses.isEmpty()) "" else " WHERE ${whereClauses.joinToString(" AND ")}"
        return Pair(where, params)
    }
}
