package com.homelab.core.service.module

import com.homelab.core.config.ModuleConfigMemory
import com.homelab.core.config.ObjectDefinitionMemory
import com.homelab.core.service.module.sql.ObjectRelationUpdater.Companion.updateRelations
import com.homelab.core.service.module.sql.ObjectTableGenerate
import com.homelab.core.service.module.sql.SQLHelper.Companion.convertFilterValue
import com.homelab.core.service.module.sql.SQLHelper.Companion.dataTypeConversion
import com.homelab.sdk.data.AutoGeneratedType
import com.homelab.sdk.data.Cardinality
import com.homelab.sdk.data.ColumnDefinition
import com.homelab.sdk.data.RelationDefinition
import com.homelab.sdk.data.TableDefinition
import com.homelab.sdk.data.ModuleDatabaseService as ModuleDatabaseServiceInterface
import org.springframework.stereotype.Service
import java.util.UUID
import javax.sql.DataSource
import com.homelab.core.service.module.sql.SQLHelper.Companion.safeSqlName
import java.sql.Connection

@Service
class ModuleDatabaseService(
    private val dataSource: DataSource,
    private val objectDefinitionMemory: ObjectDefinitionMemory
) : ModuleDatabaseServiceInterface {
    // Good
    override fun ensureModuleDatabaseReady(moduleId: String): Boolean {
        val schemaName = safeSqlName(moduleId)

        return try {
            dataSource.connection.use { connection ->
                connection.autoCommit = true

                val exists = connection.prepareStatement(
                    "SELECT 1 FROM information_schema.schemata WHERE schema_name = ?"
                ).use { stmt ->
                    stmt.setString(1, schemaName)
                    stmt.executeQuery().use { rs -> rs.next() }
                }

                if (!exists) {
                    connection.createStatement().use { st ->
                        st.execute("""CREATE SCHEMA "$schemaName"""")
                    }
                    println("Created module schema '$schemaName'")
                }

                true
            }
        } catch (e: Exception) {
            println("Failed ensuring module schema '$schemaName': ${e.message}")
            false
        }
    }
    // Need reconciliation but Good
    override fun setUpModuleDataObject(moduleId: String, objectsDefinition: TableDefinition): Boolean {
        val schemaName = safeSqlName(moduleId)
        val tableName = safeSqlName(objectsDefinition.name)

//        println("Setting up table \"$schemaName\".\"$tableName\"")
        val sql = ObjectTableGenerate.buildCreateTableSql(schemaName, tableName, objectsDefinition)
//        println("Sql for table creation "+sql)
        return try {
            dataSource.connection.use { connection ->
                connection.createStatement().use { statement ->
                    // TODO: we should ideally check if the table exists and matches the definition,
                    //  but i don't want to do reconciliation rn
                    statement.execute(sql)
                }
            }
            objectDefinitionMemory.put(moduleId, objectsDefinition)

            true
        } catch (e: Exception) {
            println("Failed setting up table \"$schemaName\".\"$tableName\": ${e.message}")
            false
        }
    }

    override fun setUpModuleDataObjectRelations(moduleId: String, objectsDefinition: TableDefinition): Boolean {
        val schemaName = safeSqlName(moduleId)
        val tableName = safeSqlName(objectsDefinition.name)
        for (relation in objectsDefinition.relations) {
            val sql = updateRelations(schemaName,tableName, relation)
            try {
                dataSource.connection.use { connection ->
                    connection.createStatement().use { statement ->
                        // TODO: we should ideally check if the table exists and matches the definition,
                        //  but i don't want to do reconciliation rn X2
                        statement.execute(sql)
                    }
                }

            } catch (e: Exception) {
                println("Failed setting up table \"$schemaName\".\"$tableName\": ${e.message}")
            }
        }
        return true
    }

    // Not Bad but need to split
    override fun insertRow(moduleId: String, tableName: String, item: Map<String, Any?>, definition: TableDefinition): Boolean {
        val schemaName = safeSqlName(moduleId)
        val tblName = safeSqlName(tableName)

        try {
            dataSource.connection.use { connection ->
                val cols = mutableListOf<String>()
                val values = mutableListOf<Any?>()

                val autoTypes = definition.autoGeneratedColumns.map { it.type }.toSet()

                fun addColumn(name: String, value: Any?) {
                    cols.add("\"${safeSqlName(name)}\"")
                    values.add(value)
                }

                for (colDef in definition.columns) {
                    val key = colDef.name
                    if (item.containsKey(key)) {
                        // unwrap Pair(value, operator) if present for insert
                        val raw0 = item[key]
                        val raw = if (raw0 is Pair<*, *>) raw0.first else raw0
                        val converted: Any? = dataTypeConversion(colDef.type.lowercase(), raw)
                        addColumn(colDef.name, converted)
                    }
                }

                if (AutoGeneratedType.FILE in autoTypes) {
                    if (item.containsKey("file")) {
                        val v0 = item["file"]
                        val v = if (v0 is Pair<*, *>) v0.first else v0
                        when (v) {
                            is Map<*, *> -> {
                                val pathRaw = v["file"] ?: v["filePath"]
                                val fnameRaw = v["file_name"] ?: v["fileName"] ?: v["originalFilename"]
                                val path = if (pathRaw is Pair<*, *>) pathRaw.first?.toString() else pathRaw?.toString()
                                val fname = if (fnameRaw is Pair<*, *>) fnameRaw.first?.toString() else fnameRaw?.toString()
                                if (path != null) addColumn("file", path)
                                if (fname != null) addColumn("file_name", fname)
                            }
                            is String -> addColumn("file", v)
                            else -> {}
                        }
                    }
                    if (item.containsKey("filePath") && cols.none { it.contains("file") }) {
                        val fp0 = item["filePath"]
                        val fp = if (fp0 is Pair<*, *>) fp0.first?.toString() else fp0?.toString()
                        addColumn("file", fp)
                    }
                    if (item.containsKey("fileName") && cols.none { it.contains("file_name") }) {
                        val fn0 = item["fileName"]
                        val fn = if (fn0 is Pair<*, *>) fn0.first?.toString() else fn0?.toString()
                        addColumn("file_name", fn)
                    }
                }

                val sql = if (cols.isEmpty()) {
                    "INSERT INTO \"$schemaName\".\"$tblName\" DEFAULT VALUES"
                } else {
                    val placeholders = cols.map { "?" }.joinToString(",")
                    "INSERT INTO \"$schemaName\".\"$tblName\" (${cols.joinToString(",")}) VALUES ($placeholders)"
                }

                connection.prepareStatement(sql).use { stmt ->
                    for (i in values.indices) {
                        stmt.setObject(i + 1, values[i])
                    }
                    val updated = stmt.executeUpdate()
                    return updated > 0
                }
            }
        } catch (e: Exception) {
            println("Failed inserting row into \"$schemaName\".\"$tblName\": ${e.message}")
            return false
        }
    }

    // Good
    override fun queryRows(moduleId: String, tableName: String, filters: Map<String, Any?>): List<Map<String, Any?>> {
        val schemaName = safeSqlName(moduleId)
        val tblName = safeSqlName(tableName)
        val results = mutableListOf<Map<String, Any?>>()

        val tableDefinition = objectDefinitionMemory.getDefinition(moduleId, tableName)
        if (tableDefinition == null) {
            println("[ModuleDatabaseService] queryRows: tableDefinition not found for moduleId: $moduleId, tableName: $tableName")
            return results
        }
//        println("[ModuleDatabaseService] queryRows: tableDefinition: $tableDefinition")
        try {
            dataSource.connection.use { connection ->
                val (where, params) = buildWhereClause(filters)
                val sql = "SELECT * FROM \"$schemaName\".\"$tblName\"$where"
                println("[ModuleDatabaseService] Querying rows from \"$schemaName\".\"$tblName\": $sql with values: ${params.joinToString(", ")}")

                val baseRows = mutableListOf<Map<String, Any?>>()

                connection.prepareStatement(sql).use { stmt ->
                    for (i in params.indices) stmt.setObject(i + 1, params[i])
                    stmt.executeQuery().use { rs ->
                        val md = rs.metaData
                        while (rs.next()) {
                            val row = mutableMapOf<String, Any?>()
                            for (i in 1..md.columnCount) {
                                val colName = md.getColumnLabel(i)
                                row[colName] = rs.getObject(i)
                            }
                            baseRows.add(row)
                        }
                    }
                }
//                println("[ModuleDatabaseService] queryRows: baseRows: $baseRows")

                if (tableDefinition.relations.isEmpty()) {
                    return baseRows
                }
                // add eager relations to baseRows


                return loadRelations(
                    connection,
                    schemaName,
                    tblName,
                    tableDefinition,
                    baseRows
                )
            }
        } catch (e: Exception) {
            println("Failed querying rows from \"$schemaName\".\"$tblName\": ${e.message}")
        }
        return results
    }

    // Good
    // Possibly make querry Rows top level and have specific querry methods for expandability ?
    override fun deleteRowsByFilters(moduleId: String, tableName: String, filters: Map<String, Any?>): Int {
        val schemaName = safeSqlName(moduleId)
        val tblName = safeSqlName(tableName)
        try {
            dataSource.connection.use { connection ->
                val (where, params) = buildWhereClause(filters)
                val sql = "DELETE FROM \"$schemaName\".\"$tblName\"$where"
                connection.prepareStatement(sql).use { stmt ->
                    for (i in params.indices) stmt.setObject(i + 1, params[i])
                    return stmt.executeUpdate()
                }
            }
        } catch (e: Exception) {
            println("Failed deleting rows from \"$schemaName\".\"$tblName\": ${e.message}")
        }
        return 0
    }

    // UPDATE rows with WHERE clause and SET columns
    override fun updateRows(
        moduleId: String,
        tableName: String,
        filters: Map<String, Any?>,
        updateMap: Map<String, Any?>
    ): Int {
        val schemaName = safeSqlName(moduleId)
        val tblName = safeSqlName(tableName)

        if (updateMap.isEmpty()) {
            println("updateRows: updateMap is empty for \"$schemaName\".\"$tblName\"")
            return 0
        }

        try {
            dataSource.connection.use { connection ->
                // Build SET clause
                val setClauses = mutableListOf<String>()
                val setParams = mutableListOf<Any?>()

                for ((k, v) in updateMap) {
                    val col = safeSqlName(k)
                    setClauses.add("\"$col\" = ?")
                    setParams.add(v)
                }

                // Build WHERE clause
                val (where, whereParams) = buildWhereClause(filters)
                if (where.isEmpty()) {
                    println("updateRows: no filters provided, skipping update for safety on \"$schemaName\".\"$tblName\"")
                    return 0
                }

                val setClause = setClauses.joinToString(", ")
                val sql = "UPDATE \"$schemaName\".\"$tblName\" SET $setClause$where"

                println("Updating rows in \"$schemaName\".\"$tblName\": $sql")
                println("  SET params: ${setParams.joinToString(", ")}")
                println("  WHERE params: ${whereParams.joinToString(", ")}")

                connection.prepareStatement(sql).use { stmt ->
                    var paramIndex = 1

                    // Bind SET parameters
                    for (param in setParams) {
                        stmt.setObject(paramIndex++, param)
                    }

                    // Bind WHERE parameters
                    for (param in whereParams) {
                        stmt.setObject(paramIndex++, param)
                    }

                    return stmt.executeUpdate()
                }
            }
        } catch (e: Exception) {
            println("Failed updating rows in \"$schemaName\".\"$tblName\": ${e.message}")
            e.printStackTrace()
        }
        return 0
    }

    // Good


    // Good, maybe move to helper


    // Build WHERE clause and parameter list from filters map.
    // filters may contain:
    // - simple value -> equality
    // - Pair(value, ModuleActionParameterType) -> operator as specified
    // - Collection -> IN (...) (equality)
    private fun buildWhereClause(filters: Map<String, Any?>): Pair<String, List<Any?>> {
        if (filters.isEmpty()) return Pair("", emptyList())
        val whereClauses = mutableListOf<String>()
        val params = mutableListOf<Any?>()

        for ((k, v) in filters) {
            val col = safeSqlName(k)

            var operatorSql = "="
            var rawValue: Any? = v

            if (v is Pair<*, *>) {
                rawValue = v.first
                val op = v.second
                if (op is com.homelab.sdk.module.action.ModuleActionParameterType) {
                    operatorSql = when (op) {
                        com.homelab.sdk.module.action.ModuleActionParameterType.EQUAL -> "="
                        com.homelab.sdk.module.action.ModuleActionParameterType.GREATER -> ">"
                        com.homelab.sdk.module.action.ModuleActionParameterType.LESS -> "<"
                        com.homelab.sdk.module.action.ModuleActionParameterType.GREATER_EQUAL -> ">="
                        com.homelab.sdk.module.action.ModuleActionParameterType.LESS_EQUAL -> "<="
                        com.homelab.sdk.module.action.ModuleActionParameterType.NONE -> { rawValue = null; "=" }
                    }
                }
            }

            if (rawValue == null) continue

            if (rawValue is Collection<*>) {
                val items = rawValue.map { convertFilterValue(it) }
                if (items.isEmpty()) continue
                val placeholders = items.map { "?" }.joinToString(",")
                whereClauses.add("\"$col\" IN ($placeholders)")
                params.addAll(items)
                continue
            }

            whereClauses.add("\"$col\" $operatorSql ?")
            params.add(convertFilterValue(rawValue))
        }

        val where = if (whereClauses.isEmpty()) "" else " WHERE ${whereClauses.joinToString(" AND ")}"
        return Pair(where, params)
    }

    //TODO: j'aime pas, la j'utilise la DB pour requeter je devrais pas, ça casse la compartimentalisation des modules
    // Extend le GenericTableLayer pour gerer les cardinalités en requetages et utiliser les fonctions de list a la place.
    private fun loadRelations(
        connection: Connection,
        schema: String,
        table: String,
        definition: TableDefinition,
        rows: List<Map<String, Any?>>
    ): List<Map<String, Any?>> {

        val result = rows.map { it.toMutableMap() }

        val baseIds = rows.mapNotNull { it["id"] }

        for (relation in definition.relations) {

            when (relation.cardinality) {
                Cardinality.MANY_TO_MANY -> {

//                    println("[ModuleDatabaseService] MANY_TO_MANY cardinality for relation: $relation")

                    val joinTable = listOf(table, relation.targetTable)
                        .sorted()
                        .joinToString("_")

                    val fkSource = "${table}_id"
                    val fkTarget = "${relation.targetTable}_id"

                    val placeholders = baseIds.joinToString(",") { "?" }

                    val sql = """
                    SELECT * FROM "$schema"."$joinTable"
                    WHERE "$fkSource" IN ($placeholders)
                """.trimIndent()

//                    println("[ModuleDatabaseService] SQL for MANY_TO_MANY cardinality: $sql")
                    val map = mutableMapOf<Any, MutableList<Map<String, Any?>>>()

                    connection.prepareStatement(sql).use { stmt ->
                        baseIds.forEachIndexed { i, id ->
                            stmt.setObject(i + 1, id)
                        }

                        stmt.executeQuery().use { rs ->
                            while (rs.next()) {

                                val parentId = rs.getObject(fkSource)
                                val targetId = rs.getObject(fkTarget)

                                val targetRow = fetchSingleRow(
                                    connection,
                                    schema,
                                    relation.targetTable,
                                    targetId
                                )

                                if (targetRow != null) {
                                    map.computeIfAbsent(parentId) { mutableListOf() }
                                        .add(targetRow)
                                }
                            }
                        }
                    }

                    result.forEach { row ->
                        val id = row["id"]
                        row[relation.targetTable] = map[id] ?: emptyList<Any>()
                    }
                }
                Cardinality.MANY_TO_ONE -> {

                    val fk = "${relation.targetTable}_id"

                    val targetIds = rows.mapNotNull { it[fk] }.distinct()

                    val targets = fetchBatch(
                        connection,
                        schema,
                        relation.targetTable,
                        targetIds
                    )

                    val targetMap = targets.associateBy { it["id"] }

                    result.forEach { row ->
                        val fkValue = row[fk]
                        row[relation.targetTable] = targetMap[fkValue]
                    }
                }
                Cardinality.ONE_TO_MANY -> {

                    val fk = "${table}_id"

                    val children = fetchChildren(
                        connection,
                        schema,
                        relation.targetTable,
                        fk,
                        baseIds
                    )

                    val grouped = children.groupBy { it[fk] }

                    result.forEach { row ->
                        val id = row["id"]
                        row[relation.targetTable] = grouped[id] ?: emptyList<Any>()
                    }
                }
                Cardinality.ONE_TO_ONE -> {

                    val fk = "${relation.targetTable}_id"

                    val targetIds = rows.mapNotNull { it[fk] }.distinct()

                    val targets = fetchBatch(
                        connection,
                        schema,
                        relation.targetTable,
                        targetIds
                    )

                    val map = targets.associateBy { it["id"] }

                    result.forEach { row ->
                        val fkValue = row[fk]
                        row[relation.targetTable] = map[fkValue]
                    }
                }
            }
        }

        return result
    }
    private fun fetchBatch(
        connection: Connection,
        schema: String,
        table: String,
        ids: List<Any>
    ): List<Map<String, Any?>> {

        if (ids.isEmpty()) return emptyList()

        val placeholders = ids.joinToString(",") { "?" }

        val sql = """SELECT * FROM "$schema"."$table" WHERE id IN ($placeholders)"""

        val result = mutableListOf<Map<String, Any?>>()

        connection.prepareStatement(sql).use { stmt ->
            ids.forEachIndexed { i, id ->
                stmt.setObject(i + 1, id)
            }

            stmt.executeQuery().use { rs ->
                val md = rs.metaData

                while (rs.next()) {
                    val row = mutableMapOf<String, Any?>()

                    for (i in 1..md.columnCount) {
                        row[md.getColumnLabel(i)] = rs.getObject(i)
                    }

                    result.add(row)
                }
            }
        }

        return result
    }
    private fun fetchSingleRow(
        connection: Connection,
        schema: String,
        table: String,
        id: Any
    ): Map<String, Any?>? {

        val sql = """SELECT * FROM "$schema"."$table" WHERE id = ?"""

        connection.prepareStatement(sql).use { stmt ->
            stmt.setObject(1, id)

            stmt.executeQuery().use { rs ->
                if (!rs.next()) return null

                val md = rs.metaData
                val row = mutableMapOf<String, Any?>()

                for (i in 1..md.columnCount) {
                    row[md.getColumnLabel(i)] = rs.getObject(i)
                }

                return row
            }
        }
    }
    private fun fetchChildren(
        connection: Connection,
        schema: String,
        table: String,
        foreignKey: String,
        parentIds: List<Any>
    ): List<Map<String, Any?>> {

        if (parentIds.isEmpty()) return emptyList()

        val placeholders = parentIds.joinToString(",") { "?" }

        val sql = """
        SELECT * FROM "$schema"."$table"
        WHERE "$foreignKey" IN ($placeholders)
    """.trimIndent()

        val result = mutableListOf<Map<String, Any?>>()

        connection.prepareStatement(sql).use { stmt ->
            parentIds.forEachIndexed { i, id ->
                stmt.setObject(i + 1, id)
            }

            stmt.executeQuery().use { rs ->
                val md = rs.metaData

                while (rs.next()) {
                    val row = mutableMapOf<String, Any?>()

                    for (i in 1..md.columnCount) {
                        row[md.getColumnLabel(i)] = rs.getObject(i)
                    }

                    result.add(row)
                }
            }
        }

        return result
    }
}
