package com.homelab.core.service.module
import com.homelab.core.model.data.ColumnDefinition
import com.homelab.core.model.data.TableDefinition
import com.homelab.core.model.data.AutoGeneratedType
import org.springframework.stereotype.Service
import java.util.UUID
import javax.sql.DataSource

@Service
class ModuleDatabaseService(
    private val dataSource: DataSource
) {
    // Good
    fun ensureModuleDatabaseReady(moduleId: String): Boolean {
        val schemaName = safeSqlName(moduleId)

        return try {
            dataSource.connection.use { connection ->
                connection.autoCommit = true

                val exists = connection.prepareStatement(
                    "SELECT 1 FROM information_schema.schemata WHERE schema_name = ?"
                ).use { stmt ->
                    stmt.setString(1, schemaName)
                    stmt.executeQuery().use { rs -> rs.next() }
                }

                if (!exists) {
                    connection.createStatement().use { st ->
                        st.execute("""CREATE SCHEMA "$schemaName"""")
                    }
                    println("Created module schema '$schemaName'")
                }

                true
            }
        } catch (e: Exception) {
            println("Failed ensuring module schema '$schemaName': ${e.message}")
            false
        }
    }

    // Need reconciliation but Good
    fun setUpModuleDataObject(moduleId: String, objectsDefinition: TableDefinition): Boolean {
        val schemaName = safeSqlName(moduleId)
        val tableName = safeSqlName(objectsDefinition.name)

//        println("Setting up table \"$schemaName\".\"$tableName\"")
        val sql = buildCreateTableSql(schemaName, tableName, objectsDefinition)
//        println("Sql for table creation "+sql)
        return try {
            dataSource.connection.use { connection ->
                connection.createStatement().use { statement ->
                    // TODO: we should ideally check if the table exists and matches the definition,
                    //  but i don't want to do reconciliation rn
                    statement.execute(sql)
                }
            }

            true
        } catch (e: Exception) {
            println("Failed setting up table \"$schemaName\".\"$tableName\": ${e.message}")
            false
        }
    }

    // Nope, reconciliation + cols logic should not be kept here but in the autogn column def (maybe Abstract and then each gives it's own querry ? )
    private fun buildCreateTableSql(
        schemaName: String,
        tableName: String,
        definition: TableDefinition
    ): String {

        //TODO: modify for reconciliation
        val existingNames = definition.columns.map { safeSqlName(it.name) }.toMutableSet()

        val cols = mutableListOf<String>()

        val autoTypes = definition.autoGeneratedColumns.map { it.type }.toSet()

//        println("Auto generated columns: $autoTypes")

        if (AutoGeneratedType.ID in autoTypes && "id" !in existingNames) {
            cols.add("id UUID PRIMARY KEY DEFAULT gen_random_uuid()")
            existingNames.add("id")
        }

        if (AutoGeneratedType.CREATED_AT in autoTypes && "created_at" !in existingNames) {
            cols.add("created_at TIMESTAMP NOT NULL DEFAULT now()")
            existingNames.add("created_at")
        }

        if (AutoGeneratedType.UPDATED_AT in autoTypes && "updated_at" !in existingNames) {
            cols.add("updated_at TIMESTAMP NOT NULL DEFAULT now()")
            existingNames.add("updated_at")
        }

        if (AutoGeneratedType.FILE in autoTypes && "file" !in existingNames) {

            cols.add("file VARCHAR(526)") // store file path
            cols.add("file_name VARCHAR(256)")
            existingNames.add("file")
            existingNames.add("file_name")
        }

        cols.addAll(definition.columns.map { buildColumnSql(it) })

        return """
            CREATE TABLE IF NOT EXISTS "${schemaName}"."${tableName}" (
                ${cols.joinToString(",\n")}
            )
        """.trimIndent()
    }

    // Good
    private fun buildColumnSql(column: ColumnDefinition): String {
        val columnName = safeSqlName(column.name)

        val sqlType = when (column.type.lowercase()) {
            "string" -> "VARCHAR(1028)"
            "int", "integer" -> "INTEGER"
            "long" -> "BIGINT"
            "boolean" -> "BOOLEAN"
            "date" -> "DATE"
            "datetime" -> "TIMESTAMP"
            else -> error("Unsupported column type: ${column.type}")
        }

        val nullable = if (column.nullable) "" else " NOT NULL"
        val unique = if (column.unique) " UNIQUE" else ""

        return """"$columnName" $sqlType$nullable$unique"""
    }

    // Not Bad but need to split
    fun insertRow(moduleId: String, tableName: String, item: Map<String, Any?>, definition: TableDefinition): Boolean {
        val schemaName = safeSqlName(moduleId)
        val tblName = safeSqlName(tableName)

        try {
            dataSource.connection.use { connection ->
                val cols = mutableListOf<String>()
                val values = mutableListOf<Any?>()

                val autoTypes = definition.autoGeneratedColumns.map { it.type }.toSet()

                fun addColumn(name: String, value: Any?) {
                    cols.add("\"${safeSqlName(name)}\"")
                    values.add(value)
                }

                for (colDef in definition.columns) {
                    val key = colDef.name
                    if (item.containsKey(key)) {
                        // unwrap Pair(value, operator) if present for insert
                        val raw0 = item[key]
                        val raw = if (raw0 is Pair<*, *>) raw0.first else raw0
                        val converted: Any? = when (colDef.type.lowercase()) {
                            "string" -> raw?.toString()
                            "file" -> raw?.toString()
                            "int", "integer" -> when (raw) {
                                is Number -> raw.toInt()
                                is String -> raw.toIntOrNull()
                                else -> null
                            }
                            "long" -> when (raw) {
                                is Number -> raw.toLong()
                                is String -> raw.toLongOrNull()
                                else -> null
                            }
                            "boolean" -> when (raw) {
                                is Boolean -> raw
                                is String -> raw.equals("true", true)
                                is Number -> raw.toInt() != 0
                                else -> null
                            }
                            "date" -> when (raw) {
                                is java.sql.Date -> raw
                                is String -> try { java.sql.Date.valueOf(raw) } catch (_: Exception) { null }
                                else -> null
                            }
                            "datetime" -> when (raw) {
                                is java.sql.Timestamp -> raw
                                is String -> try { java.sql.Timestamp.valueOf(raw) } catch (_: Exception) { null }
                                else -> null
                            }
                            else -> raw
                        }
                        addColumn(colDef.name, converted)
                    }
                }

                if (AutoGeneratedType.FILE in autoTypes) {
                    if (item.containsKey("file")) {
                        val v0 = item["file"]
                        val v = if (v0 is Pair<*, *>) v0.first else v0
                        when (v) {
                            is Map<*, *> -> {
                                val pathRaw = v["file"] ?: v["filePath"]
                                val fnameRaw = v["file_name"] ?: v["fileName"] ?: v["originalFilename"]
                                val path = if (pathRaw is Pair<*, *>) pathRaw.first?.toString() else pathRaw?.toString()
                                val fname = if (fnameRaw is Pair<*, *>) fnameRaw.first?.toString() else fnameRaw?.toString()
                                if (path != null) addColumn("file", path)
                                if (fname != null) addColumn("file_name", fname)
                            }
                            is String -> addColumn("file", v)
                            else -> {}
                        }
                    }
                    if (item.containsKey("filePath") && cols.none { it.contains("file") }) {
                        val fp0 = item["filePath"]
                        val fp = if (fp0 is Pair<*, *>) fp0.first?.toString() else fp0?.toString()
                        addColumn("file", fp)
                    }
                    if (item.containsKey("fileName") && cols.none { it.contains("file_name") }) {
                        val fn0 = item["fileName"]
                        val fn = if (fn0 is Pair<*, *>) fn0.first?.toString() else fn0?.toString()
                        addColumn("file_name", fn)
                    }
                }

                val sql = if (cols.isEmpty()) {
                    "INSERT INTO \"$schemaName\".\"$tblName\" DEFAULT VALUES"
                } else {
                    val placeholders = cols.map { "?" }.joinToString(",")
                    "INSERT INTO \"$schemaName\".\"$tblName\" (${cols.joinToString(",")}) VALUES ($placeholders)"
                }

                connection.prepareStatement(sql).use { stmt ->
                    for (i in values.indices) {
                        stmt.setObject(i + 1, values[i])
                    }
                    val updated = stmt.executeUpdate()
                    return updated > 0
                }
            }
        } catch (e: Exception) {
            println("Failed inserting row into \"$schemaName\".\"$tblName\": ${e.message}")
            return false
        }
    }

    // Good
    fun queryRows(moduleId: String, tableName: String, filters: Map<String, Any?>): List<Map<String, Any?>> {
        val schemaName = safeSqlName(moduleId)
        val tblName = safeSqlName(tableName)
        val results = mutableListOf<Map<String, Any?>>()
        try {
            dataSource.connection.use { connection ->
                val (where, params) = buildWhereClause(filters)
                val sql = "SELECT * FROM \"$schemaName\".\"$tblName\"$where"
                println("Querying rows from \"$schemaName\".\"$tblName\": $sql with values: ${params.joinToString(", ")}")
                connection.prepareStatement(sql).use { stmt ->
                    for (i in params.indices) stmt.setObject(i + 1, params[i])
                    stmt.executeQuery().use { rs ->
                        val md = rs.metaData
                        while (rs.next()) {
                            val row = mutableMapOf<String, Any?>()
                            for (i in 1..md.columnCount) {
                                val colName = md.getColumnLabel(i)
                                row[colName] = rs.getObject(i)
                            }
                            results.add(row)
                        }
                    }
                }
            }
        } catch (e: Exception) {
            println("Failed querying rows from \"$schemaName\".\"$tblName\": ${e.message}")
        }
        return results
    }

    // Good
    // Possibly make querry Rows top level and have specific querry methods for expandability ?
    fun deleteRowsByFilters(moduleId: String, tableName: String, filters: Map<String, Any?>): Int {
        val schemaName = safeSqlName(moduleId)
        val tblName = safeSqlName(tableName)
        try {
            dataSource.connection.use { connection ->
                val (where, params) = buildWhereClause(filters)
                val sql = "DELETE FROM \"$schemaName\".\"$tblName\"$where"
                connection.prepareStatement(sql).use { stmt ->
                    for (i in params.indices) stmt.setObject(i + 1, params[i])
                    return stmt.executeUpdate()
                }   
            }
        } catch (e: Exception) {
            println("Failed deleting rows from \"$schemaName\".\"$tblName\": ${e.message}")
        }
        return 0
    }

    // Good
    private fun safeSqlName(name: String): String {
        val normalized = name.trim()
            .replace(Regex("[^a-zA-Z0-9_]"), "_")
            .lowercase()

        require(normalized.matches(Regex("[a-z_][a-z0-9_]*"))) {
            "Invalid SQL name: $name"
        }

        return normalized
    }

    // Good, maybe move to helper
    private fun convertFilterValue(value: Any?): Any? {
        if (value == null) return null
        if (value is String) {
            val s = value.trim()
            //UUID CHECKER
            // definetly not the best way to do this but it works => send to helper or use lib
            val uuidRegex = Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")
            if (uuidRegex.matches(s)) {
                return try {
                    UUID.fromString(s)
                } catch (_: Exception) {
                    s
                }
            }
            // BOOLEAN CHECKER
            if (s.equals("true", true) || s.equals("false", true)) return s.equals("true", true)
            s.toIntOrNull()?.let { return it }
            s.toLongOrNull()?.let { return it }
            // DATE / DATETIME CHECKER:
            // timestamp with optional fractional seconds (e.g. 2026-05-11 14:40:39.280527)
            try {
                return java.sql.Timestamp.valueOf(s)
            } catch (_: Exception) {
                // not a full timestamp
            }
            // date-only (yyyy-[m]m-[d]d)
            try {
                return java.sql.Date.valueOf(s)
            } catch (_: Exception) {
                // not a date
            }
            return s
        }
        return value
    }

    // Build WHERE clause and parameter list from filters map.
    // filters may contain:
    // - simple value -> equality
    // - Pair(value, ModuleActionParameterType) -> operator as specified
    // - Collection -> IN (...) (equality)
    private fun buildWhereClause(filters: Map<String, Any?>): Pair<String, List<Any?>> {
        if (filters.isEmpty()) return Pair("", emptyList())
        val whereClauses = mutableListOf<String>()
        val params = mutableListOf<Any?>()

        for ((k, v) in filters) {
            val col = safeSqlName(k)

            var operatorSql = "="
            var rawValue: Any? = v

            if (v is Pair<*, *>) {
                rawValue = v.first
                val op = v.second
                if (op is com.homelab.core.model.module.action.ModuleActionParameterType) {
                    operatorSql = when (op) {
                        com.homelab.core.model.module.action.ModuleActionParameterType.EQUAL -> "="
                        com.homelab.core.model.module.action.ModuleActionParameterType.GREATER -> ">"
                        com.homelab.core.model.module.action.ModuleActionParameterType.LESS -> "<"
                        com.homelab.core.model.module.action.ModuleActionParameterType.GREATER_EQUAL -> ">="
                        com.homelab.core.model.module.action.ModuleActionParameterType.LESS_EQUAL -> "<="
                        com.homelab.core.model.module.action.ModuleActionParameterType.NONE -> { rawValue = null; "=" }
                    }
                }
            }

            if (rawValue == null) continue

            if (rawValue is Collection<*>) {
                val items = rawValue.map { convertFilterValue(it) }
                if (items.isEmpty()) continue
                val placeholders = items.map { "?" }.joinToString(",")
                whereClauses.add("\"$col\" IN ($placeholders)")
                params.addAll(items)
                continue
            }

            whereClauses.add("\"$col\" $operatorSql ?")
            params.add(convertFilterValue(rawValue))
        }

        val where = if (whereClauses.isEmpty()) "" else " WHERE ${whereClauses.joinToString(" AND ")}"
        return Pair(where, params)
    }

}
