package com.homelab.sdk.data

data class TableDefinition(
    val name: String,
    val columns: List<ColumnDefinition>,
    val autoGeneratedColumns: List<AutoGeneratedColumn>,
    val relations: List<RelationDefinition> = emptyList(),
    val uniqueTogether: List<UniqueTogetherDefinition> = emptyList()
) {
    override fun toString(): String {
        return "TableDefinition(name='$name', columns=$columns, autoGeneratedColumns=$autoGeneratedColumns)"
    }
}

