package com.homelab.core.service.module.sql

import com.homelab.core.service.module.sql.SQLHelper.Companion.safeSqlName
import com.homelab.sdk.data.AutoGeneratedType
import com.homelab.sdk.data.ColumnDefinition
import com.homelab.sdk.data.ColumnTyping
import com.homelab.sdk.data.TableDefinition


class ObjectTableGenerate {
    companion object {
        fun buildCreateTableSql(
            schemaName: String,
            tableName: String,
            definition: TableDefinition
        ): String {

            //TODO: modify for reconciliation
            val existingNames = definition.columns.map { safeSqlName(it.name) }.toMutableSet()

            val cols = mutableListOf<String>()

            val autoTypes = definition.autoGeneratedColumns.map { it.type }.toSet()

            if (AutoGeneratedType.ID in autoTypes && "id" !in existingNames) {
                cols.add("id UUID PRIMARY KEY DEFAULT gen_random_uuid()")
                existingNames.add("id")
            }

            if (AutoGeneratedType.CREATED_AT in autoTypes && "created_at" !in existingNames) {
                cols.add("created_at TIMESTAMP NOT NULL DEFAULT now()")
                existingNames.add("created_at")
            }

            if (AutoGeneratedType.UPDATED_AT in autoTypes && "updated_at" !in existingNames) {
                cols.add("updated_at TIMESTAMP NOT NULL DEFAULT now()")
                existingNames.add("updated_at")
            }

            if (AutoGeneratedType.FILE in autoTypes && "file" !in existingNames) {

                cols.add("file VARCHAR(526)") // store file path
                cols.add("file_name VARCHAR(256)")
                existingNames.add("file")
                existingNames.add("file_name")
            }

            cols.addAll(definition.columns.map { buildColumnSql(it) })

            return """
            CREATE TABLE IF NOT EXISTS "${schemaName}"."${tableName}" (
                ${cols.joinToString(",\n")}
            )
        """.trimIndent()
        }
        // Good
        private fun buildColumnSql(column: ColumnDefinition): String {
            val columnName = safeSqlName(column.name)

            val sqlType = when (column.type) {
                ColumnTyping.string  -> "VARCHAR(1028)"
                ColumnTyping.int-> "INTEGER"
                ColumnTyping.long -> "BIGINT"
                ColumnTyping.boolean -> "BOOLEAN"
                ColumnTyping.date -> "DATE"
                ColumnTyping.datetime -> "TIMESTAMP"
                else -> error("Unsupported column type: ${column.type}")
            }

            val nullable = if (column.nullable) "" else " NOT NULL"
            val unique = if (column.unique) " UNIQUE" else ""

            return """"$columnName" $sqlType$nullable$unique"""
        }

    }
    // TODO: Nope, reconciliation + cols logic should not be kept here but in the autogn column def (maybe Abstract and then each gives it's own querry ? )

}