package com.homelab.core.parser

import com.homelab.sdk.data.AutoGeneratedType
import com.homelab.sdk.data.Cardinality
import com.homelab.sdk.data.ColumnTyping
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class ModuleDataObjectParserTest {

    @Test
    fun `parseFromXml uses the naming override for object and table tags`() {
        val xml = """
            <object>
                <naming val="my_table"/>
                <col>
                    <naming val="title"/>
                    <typing val="string"/>
                </col>
            </object>
        """.trimIndent()

        val definition = ModuleDataObjectParser.parseFromXml(xml, "module-1")

        assertEquals("my_table", definition.name)
    }

    @Test
    fun `parseFromXml falls back to the raw tag name when no naming override is present`() {
        val xml = "<photos></photos>"

        val definition = ModuleDataObjectParser.parseFromXml(xml, "module-1")

        assertEquals("photos", definition.name)
    }

    @Test
    fun `parseFromXml parses column definitions with type unique nullable and regex`() {
        val xml = """
            <object>
                <naming val="users"/>
                <col>
                    <naming val="email"/>
                    <typing val="string">
                        <regex val="^[^@]+@[^@]+$"/>
                    </typing>
                    <unique val="true"/>
                    <nullable val="false"/>
                </col>
            </object>
        """.trimIndent()

        val definition = ModuleDataObjectParser.parseFromXml(xml, "module-1")

        assertEquals(1, definition.columns.size)
        val column = definition.columns.first()
        assertEquals("email", column.name)
        assertEquals(ColumnTyping.string, column.type)
        assertTrue(column.unique)
        assertEquals(false, column.nullable)
        assertEquals("^[^@]+@[^@]+$", column.regex)
    }

    @Test
    fun `parseFromXml defaults unique to false type to string and nullable to true`() {
        val xml = """
            <object>
                <naming val="notes"/>
                <col>
                    <naming val="body"/>
                </col>
            </object>
        """.trimIndent()

        val column = ModuleDataObjectParser.parseFromXml(xml, "module-1").columns.first()

        assertEquals(ColumnTyping.string, column.type)
        assertEquals(false, column.unique)
        assertEquals(true, column.nullable)
        assertNull(column.regex)
    }

    @Test
    fun `parseFromXml skips a column with a missing naming element`() {
        val xml = """
            <object>
                <naming val="notes"/>
                <col>
                    <typing val="string"/>
                </col>
            </object>
        """.trimIndent()

        val definition = ModuleDataObjectParser.parseFromXml(xml, "module-1")

        assertTrue(definition.columns.isEmpty())
    }

    @Test
    fun `parseFromXml parses all four autogenerated column kinds`() {
        val xml = """
            <object>
                <naming val="items"/>
                <autogenerated>
                    <id/>
                    <createdAt/>
                    <updatedAt/>
                    <file/>
                </autogenerated>
            </object>
        """.trimIndent()

        val definition = ModuleDataObjectParser.parseFromXml(xml, "module-1")

        assertEquals(
            listOf(AutoGeneratedType.ID, AutoGeneratedType.CREATED_AT, AutoGeneratedType.UPDATED_AT, AutoGeneratedType.FILE),
            definition.autoGeneratedColumns.map { it.type }
        )
    }

    @Test
    fun `parseFromXml ignores unknown autogenerated child tags`() {
        val xml = """
            <object>
                <naming val="items"/>
                <autogenerated>
                    <id/>
                    <mystery/>
                </autogenerated>
            </object>
        """.trimIndent()

        val definition = ModuleDataObjectParser.parseFromXml(xml, "module-1")

        assertEquals(listOf(AutoGeneratedType.ID), definition.autoGeneratedColumns.map { it.type })
    }

    @Test
    fun `parseFromXml parses a relation using the provided moduleId when moduleName is absent`() {
        val xml = """
            <object>
                <naming val="comments"/>
                <linksTo>
                    <targetObject>posts</targetObject>
                    <cardinality>many-to-one</cardinality>
                </linksTo>
            </object>
        """.trimIndent()

        val relation = ModuleDataObjectParser.parseFromXml(xml, "blog-module").relations.first()

        assertEquals("blog-module", relation.targetObject)
        assertEquals("posts", relation.targetTable)
        assertEquals(Cardinality.MANY_TO_ONE, relation.cardinality)
        assertEquals(false, relation.cascadeDelete)
        assertEquals(false, relation.cascadeUpdate)
    }

    @Test
    fun `parseFromXml prefers an explicit moduleName over the provided moduleId`() {
        val xml = """
            <object>
                <naming val="comments"/>
                <linksTo>
                    <moduleName>other-module</moduleName>
                    <targetObject>posts</targetObject>
                    <cardinality>one-to-many</cardinality>
                    <cascadeDelete>true</cascadeDelete>
                    <cascadeUpdate>true</cascadeUpdate>
                </linksTo>
            </object>
        """.trimIndent()

        val relation = ModuleDataObjectParser.parseFromXml(xml, "blog-module").relations.first()

        assertEquals("other-module", relation.targetObject)
        assertEquals(Cardinality.ONE_TO_MANY, relation.cardinality)
        assertTrue(relation.cascadeDelete)
        assertTrue(relation.cascadeUpdate)
    }

    @Test
    fun `parseFromXml throws when linksTo has no moduleName and no moduleId is supplied`() {
        val xml = """
            <object>
                <naming val="comments"/>
                <linksTo>
                    <targetObject>posts</targetObject>
                    <cardinality>one-to-one</cardinality>
                </linksTo>
            </object>
        """.trimIndent()

        val definition = ModuleDataObjectParser.parseFromXml(xml, null)

        // the exception is caught and logged per-child by the parser, so the relation is simply absent
        assertTrue(definition.relations.isEmpty())
    }

    @Test
    fun `parseFromXml drops a relation with an unknown cardinality`() {
        val xml = """
            <object>
                <naming val="comments"/>
                <linksTo>
                    <targetObject>posts</targetObject>
                    <cardinality>sideways</cardinality>
                </linksTo>
            </object>
        """.trimIndent()

        val definition = ModuleDataObjectParser.parseFromXml(xml, "blog-module")

        assertTrue(definition.relations.isEmpty())
    }

    @Test
    fun `parseFromXml parses uniqueTogether constraints with at least two fields`() {
        val xml = """
            <object>
                <naming val="memberships"/>
                <constraints>
                    <uniqueTogether name="uq_user_group">
                        <field>userId</field>
                        <field>groupId</field>
                    </uniqueTogether>
                </constraints>
            </object>
        """.trimIndent()

        val definition = ModuleDataObjectParser.parseFromXml(xml, "module-1")

        assertEquals(1, definition.uniqueTogether.size)
        val constraint = definition.uniqueTogether.first()
        assertEquals("uq_user_group", constraint.name)
        assertEquals(listOf("userId", "groupId"), constraint.fields)
    }

    @Test
    fun `parseFromXml drops a uniqueTogether constraint with fewer than two fields`() {
        val xml = """
            <object>
                <naming val="memberships"/>
                <constraints>
                    <uniqueTogether name="uq_solo">
                        <field>userId</field>
                    </uniqueTogether>
                </constraints>
            </object>
        """.trimIndent()

        val definition = ModuleDataObjectParser.parseFromXml(xml, "module-1")

        assertTrue(definition.uniqueTogether.isEmpty())
    }
}
