package com.homelab.core.model.data

enum class AutoGeneratedType {
    // TODO: maybe ID / CREATED_AT / UPDATED_AT should be by default instead of optional auto generated?
    ID, CREATED_AT, UPDATED_AT, FILE
}