package com.homelab.core.model.data

data class TableDefinition(
    val name: String,
    val columns: List<ColumnDefinition>,
    val autoGeneratedColumns: List<AutoGeneratedColumn>
) {
    override fun toString(): String {
        return "TableDefinition(name='$name', columns=$columns, autoGeneratedColumns=$autoGeneratedColumns)"
    }
}

